//
// MailosaurConfig+Version.swift
//
// This file was generated by version.sh
// Do not edit this file directly.
// Instead, edit the `VERSION` file and run `scripts/version.sh`
//
import Foundation
extension MailosaurConfig {
    public static let clientVersion = "1.0.0"
}
