#!/bin/bash

dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
version="$(cat "${dirname}/../VERSION")"

# Generate MailosaurConfig+Version.swift
cat > "${dirname}/../Sources/Mailosaur/MailosaurConfig+Version.swift"  <<EOF
//
// MailosaurConfig+Version.swift
//
// This file was generated by version.sh
// Do not edit this file directly.
// Instead, edit the \`VERSION\` file and run \`scripts/version.sh\`
//
import Foundation
extension MailosaurConfig {
    public static let clientVersion = "${version}"
}
EOF

echo "Successfully updated 'MailosaurConfig+Version.swift'"


# Replace the version in Mailosaur.podspec
for podspec in ${dirname}/../Mailosaur.podspec
do
  cat $podspec | sed -E "s|(s\.version *= *)'(.*)'|\1'$version'|" > $podspec.copy
  mv $podspec.copy $podspec

  echo "Successfully updated '$(basename $podspec)'"
done
